//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gilbert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_AD_Detail
    {
        public long ID { get; set; }
        public long IDAdHeader { get; set; }
        public long IDPosition { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public long IDEducation { get; set; }
        public long IDExperience { get; set; }
        public int Qty { get; set; }
        public string PositionDescript { get; set; }
        public string TaskDescrip { get; set; }
        public int IDStatus { get; set; }
    
        public virtual CR_AD_Header CR_AD_Header { get; set; }
        public virtual MD_EducationRequired MD_EducationRequired { get; set; }
        public virtual MD_ExperienceRequired MD_ExperienceRequired { get; set; }
        public virtual MD_Position MD_Position { get; set; }
    }
}
