//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gilbert.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GilbertEntities : DbContext
    {
        public GilbertEntities()
            : base("name=GilbertEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {            
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CR_AD_Detail> CR_AD_Detail { get; set; }
        public virtual DbSet<CR_AD_Header> CR_AD_Header { get; set; }
        public virtual DbSet<CR_Company> CR_Company { get; set; }
        public virtual DbSet<CR_User> CR_User { get; set; }
        public virtual DbSet<MD_Country> MD_Country { get; set; }
        public virtual DbSet<MD_EducationLevel> MD_EducationLevel { get; set; }
        public virtual DbSet<MD_EducationRequired> MD_EducationRequired { get; set; }
        public virtual DbSet<MD_EducationSegment> MD_EducationSegment { get; set; }
        public virtual DbSet<MD_EducationStatus> MD_EducationStatus { get; set; }
        public virtual DbSet<MD_ExperienceRequired> MD_ExperienceRequired { get; set; }
        public virtual DbSet<MD_Position> MD_Position { get; set; }
        public virtual DbSet<MD_State> MD_State { get; set; }
        public virtual DbSet<MD_Status> MD_Status { get; set; }
        public virtual DbSet<USER_CV_Education> USER_CV_Education { get; set; }
        public virtual DbSet<USER_CV_WorkExperience> USER_CV_WorkExperience { get; set; }
        public virtual DbSet<USR_CV_Header> USR_CV_Header { get; set; }
        public virtual DbSet<USR_User> USR_User { get; set; }
    }
}
