//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gilbert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CV_Education
    {
        public long ID { get; set; }
        public long IDCVHeader { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public long IDEducationSegment { get; set; }
        public long IDEducationLevel { get; set; }
        public Nullable<long> IDEducationStatus { get; set; }
        public string PlaceDescrip { get; set; }
        public int IDStatus { get; set; }
    
        public virtual MD_EducationLevel MD_EducationLevel { get; set; }
        public virtual MD_EducationSegment MD_EducationSegment { get; set; }
        public virtual MD_EducationStatus MD_EducationStatus { get; set; }
        public virtual USR_CV_Header USR_CV_Header { get; set; }
    }
}
