//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gilbert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CR_Postulate
    {
        public long ID { get; set; }
        public long IDUser { get; set; }
        public long IDCRADDetail { get; set; }
    
        public virtual CR_AD_Detail CR_AD_Detail { get; set; }
        public virtual USR_User USR_User { get; set; }
    }
}
