//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gilbert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CV_WorkExperience
    {
        public long ID { get; set; }
        public long IDCVHeader { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public long IDPosition { get; set; }
        public string PositionDescrip { get; set; }
        public string TaskDescrip { get; set; }
        public int IDStatus { get; set; }
    
        public virtual MD_Position MD_Position { get; set; }
        public virtual USR_CV_Header USR_CV_Header { get; set; }
    }
}
