//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gilbert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CR_HeaderPostulate
    {
        public long ID { get; set; }
        public long IDUserCreator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string SDescrip { get; set; }
        public string LDescrip { get; set; }
        public int IDStatus { get; set; }
        public System.Guid Unique_ID { get; set; }
        public Nullable<int> Postulantes { get; set; }
        public long IDCompany { get; set; }
    }
}
